### ISSUE TITLE
design for sponsors

### ISSUE THREAD

**Issue by harryharrold** [neontribe/UK-Charity-Camp#26]
Please add space/styling for sponsor logos in three categories: bronze, silver, gold.

Expect a variety of sizes and aspect ratios....

Sorry.

**Comment by rachelpeharding** [comment]
@harryharrold any idea how many sponsors per category?

**Comment by harryharrold** [comment]
Sadly not...

10/6/4 in my dreams... 6/3/2 expected.

**Comment by rachelpeharding** [comment]
<img width="594" alt="Screenshot 2023-06-05 at 13 35 33" src="https://github.com/neontribe/UK-Charity-Camp/assets/61546017/72a9f818-0b95-43df-b343-8fe2c4b74922">
<img width="152" alt="Screenshot 2023-06-05 at 13 35 43" src="https://github.com/neontribe/UK-Charity-Camp/assets/61546017/8761f388-df45-466f-a438-4ce163791a5b">

@rosejbon @hannahouazzane the twitter section has been moved in these designs to accommodate the sponsorship block. Is this ok for you to wrangle?

**Comment by hannahouazzane** [comment]
@rachelpeharding Should be good, but wondering where you think the privacy policy link should be placed?

**Comment by rachelpeharding** [comment]
@hannahouazzane have added :) 

<img width="574" alt="Screenshot 2023-06-05 at 13 52 13" src="https://github.com/neontribe/UK-Charity-Camp/assets/61546017/4ae0bc5d-5478-4eb4-bffc-1a55076cd851">
<img width="147" alt="Screenshot 2023-06-05 at 13 52 21" src="https://github.com/neontribe/UK-Charity-Camp/assets/61546017/69838227-bc50-4e85-b870-0016c7bad198">

**Comment by rosejbon** [comment]
@hannahouazzane you might want to read about grid layouts for the sponsors logos and how to make them responsive. Check this article out - https://every-layout.dev/layouts/grid/

**Comment by harryharrold** [comment]
Closed by https://github.com/neontribe/UK-Charity-Camp/pull/29
